import React from 'react';
import { Link } from 'react-router-dom';
import { BuildingIcon, CheckIcon, LockIcon, RocketIcon } from '../../components/Icons';
import '../../components/Programs/ProgramDetail.css';

const EmployeeProgressReportPage = () => {
  const openBooking = () => window.dispatchEvent(new CustomEvent('open-booking-modal', { detail: { service: 'team' } }));
  const audiences = ['HR departments', 'Business owners', 'Managers and team leaders', 'Learning and development teams', 'Growing organizations'];
  const focus = ['Behavioral insights', 'Individual strengths', 'Communication preferences', 'Working-style observations', 'Development areas', 'Progress observations at each review', 'Individual employee report in PDF format'];
  const uses = ['Prepare for one-to-one development discussions', 'Identify coaching or training priorities', 'Improve manager–employee understanding', 'Encourage employee self-awareness', 'Review progress against agreed development actions'];
  return (
    <div className="program-page container">
      <div className="program-hero"><div className="program-hero__grid"><div className="animate-reveal fade-up"><div className="program-hero__badge"><BuildingIcon size={14} color="#F59E0B" /><span>HR Matrix</span></div><h1 className="program-hero__title">From Employee Insight to <span className="gradient-text-gold">Focused Development</span></h1><p className="program-hero__subtitle">The Employee Brain Mapping Progress Report gives each employee a clear view of their working style, communication preferences, strengths and development areas — and helps managers track development over time.</p><div className="program-hero__actions"><button className="btn-primary" onClick={openBooking}><RocketIcon size={18}/><span>Discuss an Employee Program</span></button><Link to="/contact?service=team" className="btn-secondary">Request an HR Matrix Proposal</Link></div></div><div className="program-hero__image-wrapper animate-reveal fade-left"><div className="program-hero__image-card"><img src="/prog_team_building.webp" alt="HR team development" className="program-hero__image"/><div className="program-hero__image-badge"><BuildingIcon size={20} color="#F59E0B"/><span>Insight • Development • Progress</span></div></div></div></div></div>
      <div className="program-section program-section--dark"><div className="container"><div className="program-section-header animate-reveal fade-up"><span className="program-section-tag">Who It Is For</span><h2 className="program-section-title">A Structured HR Development Tool</h2></div><div className="program-cards-grid">{audiences.map(x=><div key={x} className="program-card-box animate-reveal fade-up"><div className="program-card-box__icon"><BuildingIcon size={24} color="#F59E0B"/></div><h3 className="program-card-box__title">{x}</h3><p className="program-card-box__desc">A structured setting for development conversations and clearer understanding of individual working patterns.</p></div>)}</div></div></div>
      <div className="program-section"><div className="container"><div className="program-section-header animate-reveal fade-up"><span className="program-section-tag">Report Focus</span><h2 className="program-section-title">What the Progress Report Covers</h2></div><div className="program-cards-grid">{focus.map(x=><div key={x} className="program-card-box animate-reveal fade-up"><div className="program-card-box__icon"><CheckIcon size={24} color="#10B981"/></div><h3 className="program-card-box__title">{x}</h3></div>)}</div></div></div>
      <div className="program-section program-section--dark"><div className="container"><div className="program-section-header animate-reveal fade-up"><span className="program-section-tag">How It May Be Used</span><h2 className="program-section-title">Turn Insight into Development Conversations</h2></div><div className="program-cards-grid">{uses.map(x=><div key={x} className="program-card-box animate-reveal fade-up"><p className="program-card-box__desc">{x}</p></div>)}</div></div></div>
      <div className="program-section"><div className="container"><div className="program-section-header animate-reveal fade-up"><span className="program-section-tag">Responsible Use and Privacy</span><h2 className="program-section-title">Clear Rules Before the Program Begins</h2></div><div className="program-highlight-box animate-reveal zoom-in"><p className="program-highlight-text">Before the program starts, we agree with you in writing on employee consent, purpose, who can see reports, confidentiality, storage and data retention. Reports should not be the only basis for hiring, termination, promotion, salary, performance ratings or job-fit decisions.</p><div className="program-highlight-author"><LockIcon size={16}/> Access is agreed in writing before the assessment, with employee consent.</div></div></div></div>
      <div className="program-section program-section--dark"><div className="container"><div className="program-section-header animate-reveal fade-up"><span className="program-section-tag">FAQ</span><h2 className="program-section-title">Common Questions</h2></div><div className="program-cards-grid"><div className="program-card-box"><h3 className="program-card-box__title">Who sees the report — HR or the employee?</h3><p className="program-card-box__desc">Access is agreed in writing before the assessment, with the employee’s consent.</p></div><div className="program-card-box"><h3 className="program-card-box__title">Does it replace performance appraisal?</h3><p className="program-card-box__desc">No. It supports development conversations but does not replace performance management.</p></div><div className="program-card-box"><h3 className="program-card-box__title">How is progress measured?</h3><p className="program-card-box__desc">Progress is reviewed every [interval] against the development actions agreed at the start. Confirm the final review interval before publishing.</p></div></div><div className="program-hero__actions" style={{justifyContent:'center',marginTop:'32px'}}><button className="btn-primary" onClick={openBooking}>Request an HR Matrix Proposal</button><a href="tel:9106545374" className="btn-secondary">Call 9106545374</a></div></div></div>
    </div>
  );
};
export default EmployeeProgressReportPage;
